sudo: required
services:
    - docker

before_install:
    - docker build -t dmeresz/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dmeresz/react-test npm test 

after_success:
    - docker build -t dmeresz/multi-client ./client
    - docker build -t dmeresz/multi-server ./server
    - docker build -t dmeresz/multi-nginx ./nginx
    - docker build -t dmeresz/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push dmeresz/multi-client
    - docker push dmeresz/multi-server
    - docker push dmeresz/multi-nginx
    - docker push dmeresz/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-671239472503
    bucket_path: multi-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY